# Build script for Skylight chrome extension. Default task prepares a directory
# to be built into an extension .crx package, or loaded unpacked through
# Chrome's extensions manager at chrome://extensions

require 'rake/clean'

VERSION = '2012.8.8.0'

extension = 'Skylight'
crx = "#{extension}.crx"
task :default => crx

CLEAN << extension
CLOBBER << crx

# add files to this list if they should be included in the extension package.
extension_files = FileList['{png,jpg,ttf,html,mp3,js}/*']

directory extension
directory 'js'
directory 'css'
directory 'json'


# write version.js
version = 'js/version.js'
extension_files << version
CLEAN << version

file version => [__FILE__, version.pathmap('%d')] do
  File.open(version, 'w') do |f|
    f.write "// Generated by Rake\nVERSION = '#{VERSION}';\n"
  end
end


# compile coffee to js
FileList['coffee/*.coffee'].each do |src|
  dest = src.pathmap '%{coffee,js}X.js'
  file dest => [src, dest.pathmap('%d')] do
    sh "coffee --compile --bare --output js #{src}"
  end
  extension_files << dest
  CLEAN << dest
end


# compile less to css
FileList['less/*.less'].each do |src|
  dest = src.pathmap '%{less,css}X.css'
  file dest => [src, dest.pathmap('%d')] do
    sh "lessc #{src} #{dest} --yui-compress"
  end
  extension_files << dest
  CLEAN << dest
end


# compile handlebars templates to templates.js
templates = 'js/templates.js'
extension_files << templates
CLEAN << templates

file templates =>
FileList['handlebars/**/*.handlebars', templates.pathmap('%d')] do
  sh "handlebars handlebars --output #{templates} --min"
end


# write manifest.json
manifest = 'json/manifest.json'
extension_files << manifest
CLEAN << manifest

file manifest => [__FILE__, manifest.pathmap('%d')] do
  require 'json'

  hash = {
    manifest_version: 2,
    name: extension,
    description: "A less flashy Skyrates.",
    version: VERSION,
    update_url: "http://skyrates.jusque.net/skylight/chromeupdate.xml",
    minimum_chrome_version: "21",
    icons: {
      "48"  => "Icon-48.png",
      "128" => "Icon-128.png"
    },
    permissions: ["notifications"],
    background: {
      scripts: ["background.js"]
    },
    content_scripts: [{
      matches:      ["http://skyrates.net/play.php"],
      css:          ["style.css"],
      js:           ["jquery.js", "underscore.js", "backbone.js",
                     "mousetrap.js", "handlebars.runtime.js", "templates.js",
                     "version.js", "constants.js", "prefs.js", "socket.js",
                     "alerter.js", "models.js", "helpers.js", "views.js",
                     "setup.js"],
      run_at:       "document_start",
      homepage_url: "http://skyrates.net/forum/viewforum.php?f=46"
    }],
    web_accessible_resources:
      FileList['{mp3,ttf,png,jpg}/*'].pathmap('%f').to_a
  }

  File.open(manifest, 'w') { |f| f.write JSON.pretty_generate hash }
end


# copy extension_files into extension directory
extension_files.uniq.each do |src|
  dest = src.pathmap "#{extension}%s%f"
  file dest => [src, dest.pathmap('%d')] do
    copy src, dest
  end
  file crx => dest
end


desc "Compile and marshall files for building the extension package."
file crx do
  puts <<-END

***
*** Build #{crx} from #{extension} directory in Chrome's Extensions manager.
***
  END
  exit
end
